### PR TITLE
Add support for ignoring users

### PR DESCRIPTION
**Pull request by strugee**
This is useful for e.g. other bots.

I couldn't actually fully test this locally (because the shell adapter doesn't allow you to specify your own username), but it at least doesn't crash or anything.

### CODE REVIEW

**Comment by strugee** [comment]
FWIW I'm running this in production and can let you know if it 100% works or not.

**Comment by strugee** [comment]
Update: it does not. Don't merge this until I debug :)

**Comment by strugee** [comment]
Okay, just pushed the fix. 100% tested now.

**Comment by mjc-gh** [comment]
:+1:

**Comment by strugee** [comment]
Thanks!

**Pull request merged**
